# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title: Bytes and Tempo
email: zangobot@zenhack.team
description: >- # this means to ignore newlines until "baseurl:"
 What's the difference between a dancer and a computer scientists?
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wire9frame
github_username:  zangobot


paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  # - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars

sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github: https://github.com/zangobot
